<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Atividade 01 Front-End 2DS</title>
</head>
<body background="imagens/fundo.png">

    <table border="2" width="900" align="center">

        <tr>
            <td height="89"><img src="imagens/logo.png" alt=""></td>

            <td aling="right">
                <a href="#">Home</a>
                <a href="quem somos.html">Quem somos</a>
                <a href="contato.html">contato</a>
            </td>
        </tr>

          <td colspan="2">
            <img src="imagens/capa.png" alt="">
          </td>
        </tr>

    <table>
    
</body>
</html>
