<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Atividade 01 Front-End 2DS</title>
</head>
<body background="imagens/fundo.png">

    <table border="0" width="900" align="center">

        <tr>
            <td height="89"><img src="imagens/logo.png" alt=""></td>

            <td aling="right">
                <a href="#">Home</a>
                <a href="quem somos.html">Quem somos</a>
                <a href="contato.html">contato</a>
            </td>
        </tr>

          <td colspan="2">
            <img src="imagens/capa.png" alt="">
          </td>
        </tr>

        <tr>

            <td cospan="2">
                <h2>Sobre o Colégio</h2>
                <p>
                    Lorem Lorem <b>ipsum dolor </b>sit amet, consectetur adipiscing elit. Suspendisse sit amet mollis nisl. Aliquam sit amet diam ac quam dignissim lobortis vel ac sapien. Proin placerat cursus risus. Duis blandit varius hendrerit. Vivamus sed placerat turpis, vel viverra neque. Duis at tempor magna, sit amet gravida purus. Nulla facilisi. Vivamus accumsan risus vitae risus blandit venenatis. Sed sed nisl tempor, tincidunt elit sit amet, facilisis neque. Donec rutrum mauris odio, gravida vestibulum nulla cursus vitae. Cras vestibulum lectus sed augue viverra ultrices ac nec lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vestibulum cursus elit, vitae placerat lectus laoreet a.

                    Lorem Lorem <b>ipsum dolor </b>sit amet, consectetur adipiscing elit. Suspendisse sit amet mollis nisl. Aliquam sit amet diam ac quam dignissim lobortis vel ac sapien. Proin placerat cursus risus. Duis blandit varius hendrerit. Vivamus sed placerat turpis, vel viverra neque. Duis at tempor magna, sit amet gravida purus. Nulla facilisi. Vivamus accumsan risus vitae risus blandit venenatis. Sed sed nisl tempor, tincidunt elit sit amet, facilisis neque. Donec rutrum mauris odio, gravida vestibulum nulla cursus vitae. Cras vestibulum lectus sed augue viverra ultrices ac nec lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vestibulum cursus elit, vitae placerat lectus laoreet a.
                </p>
                <center>
                    <b></p>Todos os Direitos reservados</b></b>
                    <center>
                </td>
            </td>
        </tr>    

    <table>
    
</body>
</html>
